[package]
name = "cmus-rpc-rs"
authors = ["anas-elgarhy"]
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord-rpc-client = "0.3.0"
clap = "3.2.12"
dirs = "4.0.0"